name: guinness
version: 0.1.18
author: Victor Savkin <vic.savkin@gmail.com>
homepage: https://github.com/vsavkin/guinness
description: A port of the Jasmine testing framework.
dependencies:
  collection: ">=0.9.1 <2.0.0"
  test: ^1.3.0
dev_dependencies:
  dartmocks: ">= 0.5.2 <0.6.0"
environment:
  sdk: '>=2.0.0-dev.68.0 <3.0.0'
